config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  


  root to: "houses#index"
  
  resources "houses", only: [:index, :show]

  resources "students", only: [:index, :show]

  resources "teachers", only: [:index, :show]

  
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  

  resources :search, only: [:index] do
    collection do
      get 'results'
    end
  end  
  
  

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :teacher
  belongs_to :student
  
  validates :appointment_date, presence: true
  validate :appointment_date_cannot_be_in_the_past

  def appointment_date_cannot_be_in_the_past
    if appointment_date.present? && appointment_date < Date.today
      errors.add(:appointment_date, "can't be in the past")
    end
  end
end

app/models/house.rb
class House < ApplicationRecord
    has_many :students
    has_many :teachers
    
    validates :name, :points, presence: true
    validates :points, numericality: { only_integer: true }
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :admin_user
  
  validates :title, presence: true
  validates :body, presence: true
  
  scope :published, ->{where.not(published_at:nil)}
  scope :unpublished, ->{where(published_at:nil)}
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :house
  has_many :appointments
  has_many :teachers, through: :appointments
  
  validates :name, presence: true
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  belongs_to :house
  has_many :appointments
  has_many :students, through: :appointments

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/houses_controller.rb
class HousesController < ApplicationController
  def index
    @houses = House.all
  end

  def show
    @house = House.find(params[:id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    private

    def post_params
      params.require(:post).permit(:title, :body, :, :published_at, :admin_user_id)
    end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController

    def index
    end
    
  
    def results
      @students = Student.where('name LIKE ?', "%#{params[:q]}%")
      
    end
   
  end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
    @students = Student.includes(:house).order(:name)
  end

  def show
    @student = Student.includes(:house).find(params[:id])
  end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  def index
    @teachers = Teacher.includes(:house).order(:name)
  end

  def show
    @teacher = Teacher.includes(:house).find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/houses_helper.rb
module HousesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/houses/index.html.erb
<% if @houses.empty? %>
  <p>There are no houses available.</p>
<% else %>
  <% @houses.each do |house| %>
    <h2><%= house.name %></h2>
    <p>There are <%= house.teachers.count %> teachers in this house.</p>
    <p>There are <%= house.students.count %> students in this house.</p>
    <p>The students of this house have accumulated <%= house.points %> points.</p>
    <p>Learn more about house <%= link_to "#{house.name}", house %></p>

  <% end %>
<% end %>

app/views/houses/show.html.erb
<h2><%= @house.name %></h2>
<p>There are <%= @house.students.count %> students in this house.</p>
<p>The students of this house have accumulated <%= @house.points %> points.</p>

<h3>Teachers in house <%= @house.name %></h3>
<% if @house.teachers.empty? %>
  <p>There are no teachers in this house.</p>
<% else %>
  <ul>
    <% @house.teachers.each do |teacher| %>
      <li><%= link_to teacher.name, teacher %></li>
    <% end %>
  </ul>
<% end %>

<h3>Students in house <%= @house.name %></h3>
<% if @house.students.empty? %>
  <p>There are no students in this house.</p>
<% else %>
  <ul>
    <% @house.students.each do |student| %>
        <li><%= link_to student.name, student_path(student) %></li>
    <% end %>
  </ul>
<% end %>
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HogwartsSchool</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %> 
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
      <header>
        <h1>Hogwarts School</h1>
        <p>
        <%= link_to 'Home', root_path %> |
        <%= link_to 'Students', students_path %> |
        <%= link_to 'Teachers', teachers_path %> |
        <%= link_to 'Search', search_index_path %> |
        <%= link_to 'Admin', "http://localhost:3000/admin" %>
        
        </p>
      </header>
     <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_field :body %>
  </div>

  <div>
    <%= form.label :, style: "display: block" %>
    <%= form.text_area : %>
  </div>

  <div>
    <%= form.label :published_at, style: "display: block" %>
    <%= form.datetime_field :published_at %>
  </div>

  <div>
    <%= form.label :admin_user_id, style: "display: block" %>
    <%= form.text_field :admin_user_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <strong>Title:</strong>
    <%= post.title %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= post.body %>
  </p>

  <p>
    <strong>:</strong>
    <%= post. %>
  </p>

  <p>
    <strong>Published at:</strong>
    <%= post.published_at %>
  </p>

  <p>
    <strong>Admin user:</strong>
    <%= post.admin_user_id %>
  </p>

</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Posts</h1>

<div id="posts">
  <% @posts.each do |post| %>
    <%= render post %>
    <p>
      <%= link_to "Show this post", post %>
    </p>
  <% end %>
</div>

<%= link_to "New post", new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post %>

<div>
  <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Back to posts", posts_path %>

  <%= button_to "Destroy this post", @post, method: :delete %>
</div>

app/views/search/index.html.erb
<h2>Search for Students</h2>

<%= form_tag(results_search_index_path, method: "get") do %>
  <%= label_tag(:q, "Search for:") %>
  <%= text_field_tag(:q) %>
  <%= submit_tag("Search") %>
<% end %>

app/views/search/results.html.erb
<h2>Students Found: <%= @students.size %></h2>

<% if @students.empty? %>
  <p>Sorry, no students found.</p>
<% else %>
  <ul>
    <% @students.each do |student| %>
      <li><%= link_to student.name, student %></li>
    <% end %>
  </ul>
<% end %>

app/views/students/index.html.erb
<h2>All Students</h2>

<% if @students.empty? %>
  <p>There are no students in the school.</p>
<% else %>
  <ul>
    <% @students.each do |student| %>
        <li>
            <%= link_to student.name, student %> of house
            <%= link_to student.house.name, student.house %>
        </li>
    <% end %>
  </ul>
<% end %>

app/views/students/show.html.erb
<h2><%= @student.name %></h2>
<p>This student belongs to house <%= link_to @student.house.name, @student.house %></p>

<h3>Appointments</h3>

<% if @student.teachers.empty? %>
    <p><%= @student.name %> has never had an appointment with a teacher.</p>
<% else %>
    <p>Here are the teachers <%= @student.name %> has appointments with: </p>
    <ul>
        <% @student.teachers.each do |teacher| %>
            <li><%= link_to teacher.name, teacher %></li>
        <% end %>
    </ul>
<% end %>

app/views/teachers/index.html.erb
<h2>All Teachers</h2>
<% if @teachers.empty? %>
  <p>There are no teachers in the school.</p>
<% else %>
  <ul>
    <% @teachers.each do |teacher| %>
        <li>
            <%= link_to teacher.name, teacher %> is in house
            <%= link_to teacher.house.name, teacher.house %>
        </li>
    <% end %>
  </ul>
<% end %>

app/views/teachers/show.html.erb
<h2><%= @teacher.name %></h2>
<p>This teacher belongs to house <%= link_to @teacher.house.name, @teacher.house %></p>

<h3>Appointments</h3>

<% if @teacher.appointments.empty? %>
    <p>No appointments for <%= @teacher.name %>. </p>
<% else %>
    <ul>
        <% @teacher.appointments.each do |app| %>
            <li>Appointment with <%= link_to app.student.name, app.student %> on <%= app.appointment_date %> . </li>
        <% end %>    
    </ul>
<% end %>